# Generated by Django 3.0.3 on 2020-11-01 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catname', models.CharField(max_length=100)),
                ('catdes', models.CharField(max_length=300)),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PoliceStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policestationname', models.CharField(max_length=150)),
                ('policestationcode', models.CharField(max_length=20)),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Police',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200, null=True)),
                ('joiningdate', models.DateField()),
                ('policestationid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crimerecord.PoliceStation')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firno', models.CharField(max_length=20)),
                ('nameaccused', models.CharField(max_length=150)),
                ('nameapplicants', models.CharField(max_length=150)),
                ('parentageapplicant', models.CharField(max_length=100)),
                ('contactno', models.CharField(max_length=15, null=True)),
                ('address', models.CharField(max_length=300)),
                ('relationaccused', models.CharField(max_length=100, null=True)),
                ('purposeoffir', models.CharField(max_length=200)),
                ('dateoffir', models.DateField()),
                ('remark', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=20)),
                ('remarkdate', models.DateField()),
                ('sectionoflaw', models.CharField(max_length=150)),
                ('investigationofficer', models.CharField(max_length=100)),
                ('investigationdetail', models.CharField(max_length=300)),
                ('chargesheetdate', models.DateField()),
                ('crimetype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crimerecord.Category')),
                ('policestationid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crimerecord.PoliceStation')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Criminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criminalid', models.CharField(max_length=20)),
                ('crimedate', models.DateField()),
                ('crimetime', models.TimeField()),
                ('prison', models.CharField(max_length=100)),
                ('court', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('contactno', models.CharField(max_length=15, null=True)),
                ('height', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('email', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=50)),
                ('photo', models.FileField(upload_to='')),
                ('recorddate', models.DateField()),
                ('catname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crimerecord.Category')),
                ('policeid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crimerecord.Police')),
                ('policestationid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crimerecord.PoliceStation')),
            ],
        ),
    ]
