# Generated by Django 3.0.3 on 2020-11-09 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimerecord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fir',
            name='chargesheetdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='fir',
            name='investigationdetail',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='fir',
            name='investigationofficer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fir',
            name='remark',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fir',
            name='remarkdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='fir',
            name='sectionoflaw',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='fir',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
